name: delphi-analysis-py312
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - awkward
  - matplotlib
  - pandas
  - root
  - uproot
  - uproot-browser
  - hist
  - ipykernel
  - mplhep
